# Generated by Django 5.0.6 on 2024-06-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('fornecedor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('quantidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_medida', models.CharField(max_length=50)),
                ('quantidade', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geralpistache.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geralpistache.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geralpistache.receita')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_medida', models.CharField(max_length=50)),
                ('quantidade', models.FloatField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geralpistache.produto')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geralpistache.receita')),
            ],
        ),
    ]
