# Generated by Django 5.0.6 on 2024-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geralpistache', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraitem',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='compraitem',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='receitaitem',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='receitaitem',
            name='receita',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='descricao',
            new_name='nome_receita',
        ),
        migrations.AddField(
            model_name='receita',
            name='ingrediente_Nome',
            field=models.CharField(default=11, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='qt_ingre',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='CompraItem',
        ),
        migrations.DeleteModel(
            name='ReceitaItem',
        ),
    ]
