# Generated by Django 5.0.6 on 2024-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geralpistache', '0002_remove_compraitem_compra_remove_compraitem_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='qt_ingre',
            field=models.CharField(max_length=1000),
        ),
    ]
