# Generated by Django 5.0.6 on 2024-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geralpistache', '0003_alter_receita_qt_ingre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='ingrediente_Nome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='qt_ingre',
            field=models.TextField(),
        ),
    ]
