# Generated by Django 5.0.6 on 2024-06-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geralpistache', '0004_alter_receita_ingrediente_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
